---
apiVersion: v1
kind: Service
metadata:
  labels:
    environment: prod
    app: psample
    tier: backend
  name: hello-world-prom-jaeg
spec:
  type: NodePort
  selector:
    app: hello-world-prom-jaeg
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  - name: management
    port: 8081
    targetPort: 8081
