---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-prom-jaeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-prom-jaeg
  template:
    metadata:
      labels:
        app: hello-world-prom-jaeg
    spec:
      containers:
      - name: application
        image: helloworld:v2
        env:
        - name: JAVA_OPTS
          value: -Xms128m -Xmx512m -server
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 8081
          name: management
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 700m
            memory: 640Mi          

